# see https://www.jetbrains.com/help/idea/http-client-in-product-code-editor.html#composing-http-requests

GET http://localhost:8080/api/userService/listAll

###

GET http://localhost:8080/api/userService/name/nikita

###

POST http://localhost:8080/api/userService/createOrUpdate
Content-Type: application/x-www-form-urlencoded

name=nikita&fullName=Nikita Zinoviev&email=nikita.zinoviev@gmail.com&pictureURL=www.sun.com&colour=0xFFFF00

###


POST http://localhost:8080/api/userService/createOrUpdate
Content-Type: application/x-www-form-urlencoded

name=sasha&fullName=Alexander Ioffe&email=alexander.ioffe@gmail.com&pictureURL=www.sun.com&colour=0xFF0000

###

## coresponding curl command is
# curl -X POST --location "http://localhost:8080/api/userService/createOrUpdate"
#    -H "Content-Type: application/x-www-form-urlencoded"
#    -d "name=sasha&fullName=Alexander Ioffe&email=alexander.ioffe@gmail.com&pictureURL=www.sun.com&colour=0xFF0000"
#
## see 'convert to curl' in context actions here





